'use client';
import { useState } from 'react';
import { useGame } from '../game/GameContext';
import { forestAreas, forestIngredients, forestRecipes, handmadeGifts } from '../data/forest';
import { getIngredient } from '../data/ingredients';
import { basketCapacity } from '../game/forest';
import { salePrice } from '../game/logic';
import { ScreenTitle } from '../components/GameUI';
export function ForestBook({ onBack }: {
    onBack: () => void;
}) {
    const { state, dispatch } = useGame(), f = state.forest;
    const [tab, setTab] = useState('food'), [amount, setAmount] = useState(1);
    const materialText = (materials: Record<string, number>) => Object.entries(materials).map(([id, n]) => `${getIngredient(id)?.name} ×${n}（所持${state.ingredients[id] || 0}）${(state.ingredients[id] || 0) < n ? ' 探せる場所：' + forestAreas.filter(a => a.bonus[id] || a.normal[id]).map(a => a.name).join('／') : ''}`).join('・');
    return <section className="screen forest-screen"><ScreenTitle title="森の手帳"/><div className="forest-book-tabs">{[['food', '食材'], ['secret', '秘密のレシピ'], ['recipes', '限定料理'], ['gifts', '手作り']].map(([id, label]) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>
 {tab === 'food' && <><p>発見 {forestIngredients.filter(i => f.discovered.includes(i.id)).length}/8 · かご {basketCapacity(f)}枠</p>{forestIngredients.map(i => <article className="forest-card" key={i.id}><h3>{i.icon} {i.name} {f.discovered.includes(i.id) ? '✓' : '未発見'}</h3><p>在庫 {state.ingredients[i.id] || 0}個 · 重さ {['forestHoney', 'forestMoonBerry'].includes(i.id) ? 2 : 1}</p><small>{forestAreas.filter(a => a.bonus[i.id]).map(a => a.name).join('・')}</small></article>)}<p>普通の食材も毎回1個見つかります。牛乳やアイスは分け合い箱・休憩所の保冷箱から。</p></>}
 {tab === 'secret' && <><p>切れ端は1回のお出かけで1枚。3枚で永久に解放。</p>{forestRecipes.filter(r => r.hidden).map(r => <article className="forest-card" key={r.id}><h3>{r.icon} {r.name}</h3><p>{f.fragments[r.id] || 0}/3枚 · {r.id === 'forestSecretTea' ? '小さな池' : r.id === 'forestSecretCookie' ? '大樹の根元' : '月しずくの泉'}</p><progress value={f.fragments[r.id] || 0} max={3}/></article>)}<p>深い森：持ち帰り {Math.min(5, f.returns)}/5回・料理提供 {Math.min(20, state.lifetimeStats.totalOrders)}/20皿</p></>}
 {tab === 'recipes' && <><p>素材を先に確保して販売します。同時に2種類、各3皿まで。次に来るお客さんが注文します。</p><label>追加する皿数 <select value={amount} onChange={e => setAmount(Number(e.target.value))}>{[1, 2, 3].map(n => <option key={n} value={n}>{n}皿</option>)}</select></label>{forestRecipes.map(r => { const unlocked = state.unlockedRecipes.includes(r.id), reserved = f.sales[r.id] || 0, inFlight = state.orders.filter(o => o.forestReserved && o.recipeId === r.id).length, active = new Set([...Object.keys(f.sales).filter(id => f.sales[id] > 0), ...state.orders.filter(o => o.forestReserved).map(o => o.recipeId)]), can = unlocked && reserved + inFlight + amount <= 3 && (active.has(r.id) || active.size < 2) && r.requiredIngredients.every(id => (state.ingredients[id] || 0) >= amount); return <article className="forest-card" key={r.id}><h3>{r.icon} {r.name}</h3><p>売上 {salePrice(r.id, state)}コイン · 調理 {r.cookingSeconds}秒</p><p>{materialText(Object.fromEntries(r.requiredIngredients.map(id => [id, 1])))}</p><p>販売待ち {reserved}皿 · 注文済み {inFlight}皿</p><button className="primary-button" disabled={!can} onClick={() => dispatch({ type: 'FOREST_SELL', recipeId: r.id, count: amount })}>{unlocked ? `${amount}皿を販売に出す` : '切れ端を集めて解放'}</button>{reserved > 0 && <button className="secondary-button" onClick={() => dispatch({ type: 'FOREST_WITHDRAW', recipeId: r.id })}>販売待ちを取り下げ、素材を戻す</button>}</article>; })}</>}
 {tab === 'gifts' && <><p>包装代100コイン。設備不要です。完成したギフトは「住人」で渡せます。</p>{handmadeGifts.map(g => <article className="forest-card" key={g.id}><h3>{g.icon} {g.name} {f.crafted.includes(g.id) && '✓'}</h3><p>{materialText(g.materials!)}</p><p>ギフト所持 {state.inventory[g.id] || 0}個</p><button className="primary-button" disabled={state.currency < 100 || !Object.entries(g.materials!).every(([id, n]) => (state.ingredients[id] || 0) >= n)} onClick={() => dispatch({ type: 'FOREST_CRAFT', giftId: g.id })}>手作りする · 100コイン</button></article>)}</>}
 <button className="secondary-button" onClick={onBack}>戻る</button></section>;
}
