'use client';
import { useEffect, useState, type CSSProperties } from 'react';
import { useGame } from '../game/GameContext';
import { FOREST_CONFIG, FOREST_BANDS, forestArea, forestBand } from '../data/forest';
import { allRecipes, getRecipe } from '../data/recipes';
import { getIngredient } from '../data/ingredients';
import { canEatForestMeal, canStartForest, forestDeepUnlocked, forestMeal } from '../game/forest';
import { ForestIcon, ForestObject } from '../components/ForestArt';
import { ForestSheet } from '../components/ForestSheet';
import type { ForestMeal } from '../types/game';
export { ForestBook } from './ForestBook';
const counts=(items:string[])=>Object.entries(items.reduce<Record<string,number>>((out,id)=>({...out,[id]:(out[id]||0)+1}),{}));
function FoodList({items}:{items:string[]}) {
  return <ul className="forest-items">{counts(items).map(([id,n])=><li key={id}><span className="forest-food-token">{getIngredient(id)?.icon||'🌿'}</span><span>{getIngredient(id)?.name}</span><b>×{n}</b></li>)}</ul>;
}
function MealBadges({meal}:{meal?:ForestMeal}) {
  return meal?<span className="forest-meal-badges">{meal.obstacleSkip>0&&<span><ForestIcon name="foot"/>障害 −{meal.obstacleSkip}</span>}{meal.emptyHints>0&&<span><ForestIcon name="search"/>目印 {meal.emptyHints}</span>}{meal.pathReduction>0&&<span><ForestIcon name="arrow"/>道 −{meal.pathReduction}</span>}{meal.rareBonus>0&&<span><ForestIcon name="spark"/>＋{Math.round(meal.rareBonus*100)}%</span>}</span>:null;
}
export function ForestScreen({onBook,onTown}:{onBook:()=>void;onTown:()=>void}) {
  const {state,dispatch}=useGame(),f=state.forest,e=f.expedition,layer=e?.layer;
  const [startFloor,setStartFloor]=useState(1),[mealId,setMealId]=useState<string>(),[panel,setPanel]=useState<'basket'|'meal'|'return'>(),[mealFilter,setMealFilter]=useState<'all'|'foot'|'luck'>('all'),[showFind,setShowFind]=useState(false);
  const band=forestBand(layer?.floor||startFloor),area=forestArea(band.area),selectedMeal=mealId?forestMeal(mealId,state):undefined;
  const find=e?.lastFind;
  useEffect(()=>{if(!find)return;setShowFind(true);const timer=window.setTimeout(()=>setShowFind(false),find.path?2400:1400);return()=>window.clearTimeout(timer);},[find]);
  const enter=()=>{dispatch({type:'FOREST_ENTER',startFloor,mealId});setPanel(undefined);};
  const goHome=()=>{if(e){dispatch({type:'FOREST_RETURN'});setPanel('return');}else onTown();};
  const nextLocked=layer?.floor===50&&!forestDeepUnlocked(state);
  const rareFind=find?.food.some(id=>['forestHoney','forestMoonBerry'].includes(id));
  const refill=Math.max(1,Math.ceil((FOREST_CONFIG.recoveryMs-(state.lastPlayedAt-f.recoveredAt))/1000));
  const mealReady=!mealId||canEatForestMeal(mealId,state);
  return <section className={`forest-adventure forest-view-${band.background}`} aria-label="こもれびの森の探索">
    <img className="forest-backdrop" src={`/assets/forest/${band.background}.jpg`} alt=""/>
    <div className="forest-vignette"/>
    <header className="forest-heading"><div><small>こもれびの森</small><h1>{e?area.name:'森へおでかけ'}</h1></div><span className="forest-floor-badge">{layer?.floor||startFloor}<small> / 70</small></span></header>
    <div className="forest-hud"><div className={`forest-energy ${f.energy<10?'is-low':''}`} role="meter" aria-label="残り体力" aria-valuenow={f.energy} aria-valuemin={0} aria-valuemax={70}><ForestIcon name="leaf"/><div><div className="forest-energy-numbers"><strong>{f.energy}<small> / 70</small></strong><small>{e?'':f.energy<70?`＋1 ${refill}秒`:'満タン'}</small></div><span className="forest-energy-track"><i style={{width:`${f.energy/70*100}%`}}/></span></div></div><button className="forest-basket-hud" onClick={()=>setPanel('basket')} aria-label={`かごの中を見る、素材${e?.basket.length||0}個`}><ForestIcon name="basket"/><b>{e?.basket.length||0}</b></button></div>
    {e&&<div className="forest-detail-row"><span className="forest-active-meal">{e.meal?<><ForestIcon name={e.meal.kind==='foot'?'foot':'spark'}/><span>{getRecipe(e.meal.recipeId)?.name}</span><b>Lv.{e.meal.level}</b></>:<><ForestIcon name="search"/>タップで探索 <b>−1</b></>}</span><span className="forest-cafe-peek">{layer&&layer.floor%10===0&&layer.floor<70?<><ForestIcon name="arrow"/>{layer.floor+1}層への近道</>:<><ForestIcon name="home"/>{state.orders.filter(o=>o.status==='ready').length}<ForestIcon name="ticket"/>{state.deliveries.length}</>}</span></div>}
    {e&&layer?<>
      <div className="forest-landscape forest-stage" key={`${e.id}:${layer.floor}`} aria-label={`${layer.floor}層の探索場所`}>
        <div className="forest-stage-trail" aria-hidden="true"/>
        {layer.spots.map(spot=>{const used=layer.used.includes(spot.id);return <button key={spot.id} className={`forest-gather ${used?'is-spent':''} ${spot.emptyHint?'is-empty-hint':''}`} style={{gridColumn:spot.cell%3+1,gridRow:Math.floor(spot.cell/3)+1,'--spot-x':`${spot.x}%`,'--spot-y':`${spot.y}%`} as CSSProperties} disabled={used||f.energy<1} onClick={()=>dispatch({type:'FOREST_GATHER',floor:layer.floor,spot:spot.id})} aria-label={used?`探索場所${spot.id+1}、探索済み`:spot.emptyHint?`探索場所${spot.id+1}、実りなし、調べると体力1`:`探索場所${spot.id+1}を調べる、体力1`}><ForestObject kind={spot.kind} spent={used}/>{used?<span className="forest-spent-mark"><ForestIcon name="check"/></span>:spot.emptyHint?<span className="forest-empty-marker">実りなし</span>:<span className="forest-glint"><ForestIcon name="spark"/></span>}</button>;})}
        {showFind&&find&&<div key={`${layer.floor}:${find.spot}`} className={`forest-find-toast ${rareFind?'is-rare':''} ${find.path?'has-path':''}`} role="status"><div>{find.food.map((id,i)=><span key={i}>{getIngredient(id)?.icon} {getIngredient(id)?.name}<b>＋1</b></span>)}{find.fragment&&<span>📜 {getRecipe(find.fragment)?.name}</span>}{find.coins>0&&<span>🪙 ＋{find.coins}</span>}{find.tickets>0&&<span>🎟️ ＋{find.tickets}</span>}{!find.food.length&&!find.fragment&&!find.coins&&!find.tickets&&!find.path&&<span>🍃 見つからず</span>}</div>{find.path&&<strong><ForestIcon name="arrow"/>小道を発見！</strong>}</div>}
      </div>
      <div className="forest-route-panel">
        {f.energy===0?<div className="forest-route-message"><ForestIcon name="leaf"/>ひとやすみしよう<button onClick={goHome}>店へ帰る<ForestIcon name="home"/></button></div>:layer.floor===70?<div className="forest-route-message forest-goal"><ForestIcon name="spark"/>最奥に到着！<span>残りも探してみよう</span></div>:!layer.pathFound?<div className="forest-route-search"><ForestIcon name="search"/><span>小道を探そう</span><div className="forest-search-dots" aria-label={`${layer.used.length}か所探索済み`}>{Array.from({length:layer.pathLimit},(_,i)=><i key={i} className={i<layer.used.length?'filled':''}/>)}</div></div>:nextLocked?<div className="forest-route-message"><ForestIcon name="lock"/><span>奥の森<small>持帰 {Math.min(5,f.returns)}/5 · 提供 {Math.min(20,state.lifetimeStats.totalOrders)}/20</small></span></div>:<button className={`forest-next-action ${layer.obstacleRemaining?'has-obstacle':''}`} onClick={()=>dispatch({type:layer.obstacleRemaining?'FOREST_CLEAR':'FOREST_MOVE',floor:layer.floor})} aria-label={layer.obstacleRemaining?`茂みを分ける、残り${layer.obstacleRemaining}回、体力1`:`${layer.floor+1}層へ進む、体力1`}><span className="forest-route-symbol"><ForestIcon name={layer.obstacleRemaining?'leaf':'arrow'}/></span><span>{layer.obstacleRemaining?'茂みを分ける':'奥へ進む'}<small>{layer.obstacleRemaining?`あと${layer.obstacleRemaining}回`:`${layer.floor+1}層 · ${forestArea(forestBand(layer.floor+1).area).name}`}{layer.obstacleSkipped>0&&layer.obstacleRemaining===0&&<em>足取り軽やか</em>}</small></span><b><ForestIcon name="leaf"/>−1</b></button>}
      </div>
    </>:<div className="forest-departure">
      <div className="forest-entry-art" aria-hidden="true"><ForestObject kind="berries"/><ForestObject kind="herbs"/></div>
      <div className="forest-expedition-card"><div className="forest-card-caption"><ForestIcon name="arrow"/>出発地点<span>最深 {f.deepestFloor}層</span></div><div className="forest-start-options">{FOREST_BANDS.map(b=>{const unlocked=canStartForest(state,b.from);return <button key={b.from} className={startFloor===b.from?'active':''} disabled={!unlocked} onClick={()=>setStartFloor(b.from)} aria-label={`${b.from}層 ${forestArea(b.area).name}${unlocked?'':`、${b.from-1}層の目印で開通${b.from>=51?'、持ち帰り5回・提供20皿も必要':''}`}`}><span>{unlocked?forestArea(b.area).icon:<ForestIcon name="lock"/>}</span><b>{b.from}</b></button>;})}</div><p className="forest-start-name">{area.name}<small>{band.from}〜{band.to}層</small></p>
      <button className="forest-meal-picker" onClick={()=>setPanel('meal')}><span className="forest-meal-icon">{mealId?getRecipe(mealId)?.icon:'🍽️'}</span><span><b>{mealId?getRecipe(mealId)?.name:'出発前にひとくち'}</b>{selectedMeal?<MealBadges meal={selectedMeal}/>:<small>食事で探索をお手伝い</small>}</span><ForestIcon name="arrow"/></button>
      <button className="forest-main-action" disabled={state.lifetimeStats.totalOrders<1||f.energy<1||!mealReady||!canStartForest(state,startFloor)} onClick={enter}>{mealId?'食べて出発':'出発する'}<ForestIcon name="arrow"/></button><small className="forest-entry-note">{state.lifetimeStats.totalOrders<1?'料理を1品提供すると解放':!mealReady?'食材が足りません':f.energy<1?'体力回復中':'探索中は体力回復なし'}</small></div>
      {f.lastReturn&&<button className="forest-history-button" onClick={()=>setPanel('return')}><ForestIcon name="basket"/>持ち帰ったもの</button>}
    </div>}
    <footer className="forest-dock"><button onClick={goHome}><ForestIcon name="home"/><span>店へ帰る</span></button>{e&&<button onClick={()=>setPanel('basket')}><ForestIcon name="basket"/><span>かご <b>{e.basket.length}</b></span></button>}<button onClick={onBook}><ForestIcon name="book"/><span>手帳</span></button></footer>
    {panel==='meal'&&!e&&<ForestSheet title="出発前のひとくち" onClose={()=>setPanel(undefined)}><div className="forest-meal-filters">{[['all','すべて'],['foot','足取り'],['luck','幸運']].map(([id,label])=><button className={mealFilter===id?'active':''} key={id} onClick={()=>setMealFilter(id as typeof mealFilter)}>{label}</button>)}</div><button className="forest-no-meal" onClick={()=>{setMealId(undefined);setPanel(undefined);}}>食事なし<ForestIcon name="check"/></button><div className="forest-meal-list">{allRecipes.filter(r=>state.unlockedRecipes.includes(r.id)).map(r=>({r,meal:forestMeal(r.id,state)!})).filter(({meal})=>mealFilter==='all'||meal.kind===mealFilter).sort((a,b)=>Number(canEatForestMeal(b.r.id,state))-Number(canEatForestMeal(a.r.id,state))).map(({r,meal})=>{const ready=canEatForestMeal(r.id,state);return <button key={r.id} className={`forest-meal-card ${mealId===r.id?'selected':''} is-${meal.rarity}`} disabled={!ready} onClick={()=>{setMealId(r.id);setPanel(undefined);}}><span className="forest-meal-icon">{r.icon}</span><span><b>{r.name}<small>Lv.{meal.level}</small></b><MealBadges meal={meal}/><span className="forest-meal-materials">{r.requiredIngredients.map(id=><span key={id}>{getIngredient(id)?.icon} ×1</span>)}{!ready&&<em>食材・設備待ち</em>}</span></span>{mealId===r.id&&<ForestIcon name="check"/>}</button>;})}</div></ForestSheet>}
    {panel==='basket'&&<ForestSheet title="かごの中" onClose={()=>setPanel(undefined)}><FoodList items={e?.basket||[]}/>{!e?.basket.length&&<p className="forest-empty-basket">🌿 まだ空っぽ</p>}<div className="forest-find-bonuses"><span><ForestIcon name="coin"/>{e?.coins||0}</span><span><ForestIcon name="ticket"/>{e?.tickets||0}</span></div>{Object.entries(e?.fragments||{}).map(([id,n])=><p className="forest-return-note" key={id}>📜 {getRecipe(id)?.name} ＋{n}</p>)}{e?.meal&&<MealBadges meal={e.meal}/>}</ForestSheet>}
    {panel==='return'&&f.lastReturn&&!e&&<ForestSheet title="森のおみやげ" onClose={()=>setPanel(undefined)}><div className="forest-return-summary"><span><b>{f.lastReturn.floor||'—'}</b>到達層</span><span><b>{f.lastReturn.food.length}</b>素材</span><span><b>{f.lastReturn.energySpent||0}</b>消費体力</span></div><FoodList items={f.lastReturn.food}/><div className="forest-find-bonuses"><span><ForestIcon name="coin"/>{f.lastReturn.coins.toLocaleString()}</span><span><ForestIcon name="ticket"/>{f.lastReturn.tickets}</span></div>{Object.entries(f.lastReturn.fragments||{}).map(([id,n])=><p className="forest-return-note" key={id}>📜 {getRecipe(id)?.name} {(f.fragments[id]||0)}/3 <b>＋{n}</b></p>)}{f.lastReturn.floor&&f.lastReturn.floor%10===0&&f.lastReturn.floor<70&&<p className="forest-checkpoint-note"><ForestIcon name="arrow"/>{f.lastReturn.floor+1}層への近道が開通</p>}<button className="forest-main-action" onClick={onTown}>カフェへ<ForestIcon name="home"/></button></ForestSheet>}
  </section>;
}
