'use client';
import { useState } from 'react';
import { useGame } from '../game/GameContext';
import { FOREST_CONFIG, forestAreas, forestArea, forestIngredients, forestRecipes, handmadeGifts } from '../data/forest';
import { getIngredient } from '../data/ingredients';
import { basketCapacity, basketWeight, forestDeepUnlocked, forestSecret, forestRandom } from '../game/forest';
import { salePrice } from '../game/logic';
import { tableCapacity } from '../game/seating';
import { ScreenTitle } from '../components/GameUI';
const counts = (items: string[]) => Object.entries(items.reduce<Record<string, number>>((out, id) => ({ ...out, [id]: (out[id] || 0) + 1 }), {}));
function FoodList({ items }: {
    items: string[];
}) { return <ul className="forest-loot">{counts(items).map(([id, n]) => <li key={id}>{getIngredient(id)?.icon} {getIngredient(id)?.name} <b>×{n}</b></li>)}</ul>; }
export function ForestScreen({ onBook, onTown }: {
    onBook: () => void;
    onTown: () => void;
}) {
    const { state, dispatch } = useGame(), f = state.forest, e = f.expedition;
    const energy = <div className="forest-meter"><strong>🍃 体力 {f.energy} / 70</strong><span>{f.energy < 70 ? `あと${Math.max(1, Math.ceil((60000 - (state.lastPlayedAt - f.recoveredAt)) / 1000))}秒で +1` : '1分で1回復'}</span></div>;
    if (!e)
        return <section className="screen forest-screen"><ScreenTitle title="こもれびの森"/>{energy}<div className="forest-card"><h2>ひとつ見つける、小さな冒険。</h2><p>森の分け合い箱には、街のみんなが届けた食材。草むらには季節の恵み。かごを持って探しに行こう。</p><p>普通の食材は毎回1個。採取ごとに{FOREST_CONFIG.ticketChance * 100}％の確率で調達券1枚が見つかります。</p><p>🧺 かご {basketCapacity(f)}枠 · 帰還 {f.returns}回</p><button className="primary-button" disabled={state.lifetimeStats.totalOrders < 1 || f.energy < 1} onClick={() => dispatch({ type: 'FOREST_ENTER' })}>森へ出かける</button>{state.lifetimeStats.totalOrders < 1 && <p>最初の料理を提供すると出かけられます。</p>}</div>{f.lastReturn && <div className="forest-card"><h3>持ち帰ったもの</h3><FoodList items={f.lastReturn.food}/><p>🪙 +{f.lastReturn.coins} · 🎟 +{f.lastReturn.tickets}{f.lastReturn.fragment && ` · ${forestRecipes.find(r => r.id === f.lastReturn?.fragment)?.name}の切れ端`}</p></div>}<button className="secondary-button" onClick={onBook}>森の手帳を開く</button><button className="secondary-button" onClick={onTown}>街へ戻る</button></section>;
    const area = forestArea(e.area), secret = forestSecret(f), capacity = basketCapacity(f), used = basketWeight(e.basket), ready = state.orders.filter(o => o.status === 'ready').length;
    if (e.returning)
        return <section className="screen forest-screen"><ScreenTitle title="森からのおみやげ"/>{energy}<div className="forest-card"><FoodList items={e.basket}/><p>🪙 {e.coins.toLocaleString()}コイン · 🎟 調達券 {e.tickets}枚</p>{e.fragment && <p>📜 {forestRecipes.find(r => r.id === e.fragment)?.name}の切れ端 {(f.fragments[e.fragment] || 0) + 1}/3</p>}<p>持ち帰ると在庫に加わります。</p><button className="primary-button" onClick={() => dispatch({ type: 'FOREST_CLAIM' })}>受け取る</button></div></section>;
    const cells = [...Array(9).keys()].sort((a, b) => { const ra = forestRandom(e.seed, area.id + ':cell:' + a)(), rb = forestRandom(e.seed, area.id + ':cell:' + b)(); return ra - rb; }).slice(0, 3);
    return <section className="screen forest-screen"><ScreenTitle title="こもれびの森"/>{energy}<div className="forest-cafe-status">☕ 完成 {ready}皿 · 入荷待ち {state.deliveries.length}件 · 空席 {tableCapacity(state) - state.orders.length}</div><header className="forest-place"><span>{area.icon}</span><div><h2>{area.name}</h2><p>🧺 {used} / {capacity}枠 · 🎟 {e.tickets}枚 · 🪙 {e.coins}</p></div></header><nav className="forest-route" aria-label="森の道順">{forestAreas.map(a => <span key={a.id} className={a.id === area.id ? 'current' : ''}>{a.icon}{a.name}</span>)}</nav>
 {Object.keys(area.normal).length > 0 ? <><p className="forest-description">分け合い箱から食材1個。限定食材の追加は {area.rate}% / 丁寧 {area.rate + 5}%</p><div className="forest-map" aria-label={`${area.name}の採取地図`}>{Array.from({ length: 9 }, (_, i) => { const spot = cells.indexOf(i), taken = e.used.includes(`${area.id}:${spot}`); return <div key={i} className={spot >= 0 ? 'forest-cell harvest-cell' : 'forest-cell'}>{spot >= 0 ? <><span>{taken ? '✓' : '🧺'}</span><strong>{taken ? '採取済み' : `探す ${spot + 1}`}</strong>{!taken && <><button disabled={f.energy < 2 || !!e.pending} onClick={() => dispatch({ type: 'FOREST_GATHER', spot, careful: false })}>採取 −2</button><button disabled={f.energy < 3 || !!e.pending} onClick={() => dispatch({ type: 'FOREST_GATHER', spot, careful: true })}>丁寧 −3</button></>}</> : <span aria-hidden="true">{i % 2 ? '🍃' : '·'}</span>}</div>; })}</div></> : <p className="forest-description">{area.id === 'fork' ? '川辺へ行く？ 森の奥へ進む？' : '街の喧騒が少しずつ遠ざかる。'}</p>}
 {secret && <button className="forest-fragment" disabled={f.energy < 2 || !!e.pending} onClick={() => dispatch({ type: 'FOREST_FRAGMENT' })}>📜 レシピの切れ端を拾う −2<br /><small>{forestRecipes.find(r => r.id === secret)?.name} {(f.fragments[secret] || 0) + 1}/3</small></button>}
 {e.pending && <div className="forest-card forest-found" role="status"><h3>見つけた！</h3><FoodList items={e.pending.food}/><p>🪙 +{e.pending.coins} · 🎟 +{e.pending.tickets}（かごを使いません）</p>{basketWeight([...e.basket, ...e.pending.food]) > capacity && <p>かごがいっぱいです。下の持ち物を1個置いて空きを作れます。</p>}<button className="primary-button" disabled={basketWeight([...e.basket, ...e.pending.food]) > capacity} onClick={() => dispatch({ type: 'FOREST_TAKE' })}>かごに入れる</button><button className="secondary-button" onClick={() => dispatch({ type: 'FOREST_DISCARD' })}>食材を置いていく</button></div>}
 <div className="forest-paths">{area.next.map(([id, cost]) => { const locked = ['stone', 'spring'].includes(id) && !forestDeepUnlocked(state); return <button className="primary-button" key={id} disabled={locked || f.energy < cost || !!e.pending} onClick={() => dispatch({ type: 'FOREST_MOVE', area: id })}>{forestArea(id).icon} {forestArea(id).name}へ −{cost}{locked && <small>持ち帰り5回・料理提供20皿で解放</small>}</button>; })}<button className="secondary-button" disabled={!!e.pending} onClick={() => dispatch({ type: 'FOREST_RETURN' })}>街へ帰る（体力0でもOK）</button></div><details className="forest-card"><summary>かごの中 {used}/{capacity}枠</summary>{e.pending ? <ul className="forest-loot">{e.basket.map((id, i) => <li key={i}>{getIngredient(id)?.icon} {getIngredient(id)?.name}<button onClick={() => dispatch({ type: 'FOREST_DROP', index: i })}>1個置く</button></li>)}</ul> : <FoodList items={e.basket}/>}</details><button className="secondary-button" onClick={onBook}>森の手帳</button></section>;
}
export function ForestBook({ onBack }: {
    onBack: () => void;
}) {
    const { state, dispatch } = useGame(), f = state.forest;
    const [tab, setTab] = useState('food'), [amount, setAmount] = useState(1);
    const materialText = (materials: Record<string, number>) => Object.entries(materials).map(([id, n]) => `${getIngredient(id)?.name} ×${n}（所持${state.ingredients[id] || 0}）${(state.ingredients[id] || 0) < n ? ' 探せる場所：' + forestAreas.filter(a => a.bonus[id] || a.normal[id]).map(a => a.name).join('／') : ''}`).join('・');
    return <section className="screen forest-screen"><ScreenTitle title="森の手帳"/><div className="forest-book-tabs">{[['food', '食材'], ['secret', '秘密のレシピ'], ['recipes', '限定料理'], ['gifts', '手作り']].map(([id, label]) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>
 {tab === 'food' && <><p>発見 {forestIngredients.filter(i => f.discovered.includes(i.id)).length}/8 · かご {basketCapacity(f)}枠</p>{forestIngredients.map(i => <article className="forest-card" key={i.id}><h3>{i.icon} {i.name} {f.discovered.includes(i.id) ? '✓' : '未発見'}</h3><p>在庫 {state.ingredients[i.id] || 0}個 · 重さ {['forestHoney', 'forestMoonBerry'].includes(i.id) ? 2 : 1}</p><small>{forestAreas.filter(a => a.bonus[i.id]).map(a => a.name).join('・')}</small></article>)}<p>普通の食材も毎回1個見つかります。牛乳やアイスは分け合い箱・休憩所の保冷箱から。</p></>}
 {tab === 'secret' && <><p>切れ端は1回のお出かけで1枚。3枚で永久に解放。</p>{forestRecipes.filter(r => r.hidden).map(r => <article className="forest-card" key={r.id}><h3>{r.icon} {r.name}</h3><p>{f.fragments[r.id] || 0}/3枚 · {r.id === 'forestSecretTea' ? '小さな池' : r.id === 'forestSecretCookie' ? '大樹の根元' : '月しずくの泉'}</p><progress value={f.fragments[r.id] || 0} max={3}/></article>)}<p>深い森：持ち帰り {Math.min(5, f.returns)}/5回・料理提供 {Math.min(20, state.lifetimeStats.totalOrders)}/20皿</p></>}
 {tab === 'recipes' && <><p>素材を先に確保して販売します。同時に2種類、各3皿まで。次に来るお客さんが注文します。</p><label>追加する皿数 <select value={amount} onChange={e => setAmount(Number(e.target.value))}>{[1, 2, 3].map(n => <option key={n} value={n}>{n}皿</option>)}</select></label>{forestRecipes.map(r => { const unlocked = state.unlockedRecipes.includes(r.id), reserved = f.sales[r.id] || 0, inFlight = state.orders.filter(o => o.forestReserved && o.recipeId === r.id).length, active = new Set([...Object.keys(f.sales).filter(id => f.sales[id] > 0), ...state.orders.filter(o => o.forestReserved).map(o => o.recipeId)]), can = unlocked && reserved + inFlight + amount <= 3 && (active.has(r.id) || active.size < 2) && r.requiredIngredients.every(id => (state.ingredients[id] || 0) >= amount); return <article className="forest-card" key={r.id}><h3>{r.icon} {r.name}</h3><p>売上 {salePrice(r.id, state)}コイン · 調理 {r.cookingSeconds}秒</p><p>{materialText(Object.fromEntries(r.requiredIngredients.map(id => [id, 1])))}</p><p>販売待ち {reserved}皿 · 注文済み {inFlight}皿</p><button className="primary-button" disabled={!can} onClick={() => dispatch({ type: 'FOREST_SELL', recipeId: r.id, count: amount })}>{unlocked ? `${amount}皿を販売に出す` : '切れ端を集めて解放'}</button>{reserved > 0 && <button className="secondary-button" onClick={() => dispatch({ type: 'FOREST_WITHDRAW', recipeId: r.id })}>販売待ちを取り下げ、素材を戻す</button>}</article>; })}</>}
 {tab === 'gifts' && <><p>包装代100コイン。設備不要です。完成したギフトは「住人」で渡せます。</p>{handmadeGifts.map(g => <article className="forest-card" key={g.id}><h3>{g.icon} {g.name} {f.crafted.includes(g.id) && '✓'}</h3><p>{materialText(g.materials!)}</p><p>ギフト所持 {state.inventory[g.id] || 0}個</p><button className="primary-button" disabled={state.currency < 100 || !Object.entries(g.materials!).every(([id, n]) => (state.ingredients[id] || 0) >= n)} onClick={() => dispatch({ type: 'FOREST_CRAFT', giftId: g.id })}>手作りする · 100コイン</button></article>)}</>}
 <button className="secondary-button" onClick={onBack}>戻る</button></section>;
}
